apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bot-config.yaml
  - bot-deployment.yaml
  - bot-service.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - redis-statefulset.yaml
  - redis-service.yaml

configMapGenerator:
  - name: postgres-initdb
    files:
      - postgres-initdb/001_bot_config_schema.sql
      - postgres-initdb/002_interface_language_preferences.sql
