services:
  - type: web
    name: python-tts
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: ohio
    plan: free
    # Docker container configuration
    envVars:
      - key: PORT
        value: 10000
