services:
  - type: web
    name: python-tts
    env: python
    region: ohio
    plan: free
    buildCommand: bash render-build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 --log-level info wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
