apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tts-hotkey-dev

resources:
  - ../../base

images:
  - name: ghcr.io/erikalira/tts-hotkey-windows-bot
    newName: tts-hotkey-windows-bot
    newTag: local

patches:
  - path: resources-patch.yaml
