apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  template:
    spec:
      containers:
        - name: bot
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 750m
              memory: 768Mi
