"""Shared timeout defaults used across bot and desktop runtimes."""

DEFAULT_DESKTOP_HTTP_REQUEST_TIMEOUT_SECONDS = 10
MIN_DESKTOP_HTTP_REQUEST_TIMEOUT_SECONDS = 1
MAX_DESKTOP_HTTP_REQUEST_TIMEOUT_SECONDS = 60

DEFAULT_BOT_TTS_GENERATION_TIMEOUT_SECONDS = 60
DEFAULT_BOT_TTS_PLAYBACK_TIMEOUT_SECONDS = 60
DEFAULT_DISCORD_VOICE_CONNECTION_TIMEOUT_SECONDS = 30.0
DEFAULT_DISCORD_IDLE_DISCONNECT_TIMEOUT_SECONDS = 30 * 60
