"""Application DTOs and typed contracts for use-case boundaries."""

from .desktop_results import (
    DesktopBotActionResultDTO,
    DesktopBotConnectionStatusDTO,
    DesktopBotVoiceContextResultDTO,
    DesktopBotVoiceContextStatusDTO,
    DesktopConfigurationSaveResultDTO,
)
from .results import (
    ConfigureTTSResult,
    JoinVoiceChannelResult,
    LeaveVoiceChannelResult,
    ResultBase,
    SpeakTextResult,
    TTSConfigurationData,
    VoiceContextResult,
    JOIN_RESULT_MISSING_GUILD_ID,
    JOIN_RESULT_OK,
    JOIN_RESULT_USER_NOT_IN_CHANNEL,
    JOIN_RESULT_VOICE_CHANNEL_NOT_FOUND,
    JOIN_RESULT_VOICE_CONNECTION_FAILED,
    LEAVE_RESULT_MISSING_GUILD_ID,
    LEAVE_RESULT_NOT_CONNECTED,
    LEAVE_RESULT_OK,
    LEAVE_RESULT_VOICE_CONNECTION_FAILED,
    SPEAK_RESULT_CROSS_GUILD_CHANNEL,
    SPEAK_RESULT_MISSING_GUILD_ID,
    SPEAK_RESULT_MISSING_TEXT,
    SPEAK_RESULT_OK,
    SPEAK_RESULT_PLAYBACK_TIMEOUT,
    SPEAK_RESULT_QUEUED,
    SPEAK_RESULT_QUEUE_FULL,
    SPEAK_RESULT_UNKNOWN_ERROR,
    SPEAK_RESULT_USER_LEFT_CHANNEL,
    SPEAK_RESULT_USER_NOT_IN_CHANNEL,
    SPEAK_RESULT_VOICE_CHANNEL_NOT_FOUND,
    SPEAK_RESULT_VOICE_CONNECTION_FAILED,
    SPEAK_RESULT_VOICE_PERMISSION_DENIED,
    VOICE_CONTEXT_RESULT_MEMBER_REQUIRED,
    VOICE_CONTEXT_RESULT_NOT_IN_CHANNEL,
    VOICE_CONTEXT_RESULT_OK,
)
from .speak_text_input_dto import SpeakTextInputDTO
from .voice_context_query_dto import VoiceContextQueryDTO

__all__ = [
    "ConfigureTTSResult",
    "DesktopBotActionResultDTO",
    "DesktopBotConnectionStatusDTO",
    "DesktopBotVoiceContextResultDTO",
    "DesktopBotVoiceContextStatusDTO",
    "DesktopConfigurationSaveResultDTO",
    "JoinVoiceChannelResult",
    "LeaveVoiceChannelResult",
    "ResultBase",
    "SpeakTextInputDTO",
    "SpeakTextResult",
    "TTSConfigurationData",
    "VoiceContextQueryDTO",
    "VoiceContextResult",
    "JOIN_RESULT_MISSING_GUILD_ID",
    "JOIN_RESULT_OK",
    "JOIN_RESULT_USER_NOT_IN_CHANNEL",
    "JOIN_RESULT_VOICE_CHANNEL_NOT_FOUND",
    "JOIN_RESULT_VOICE_CONNECTION_FAILED",
    "LEAVE_RESULT_MISSING_GUILD_ID",
    "LEAVE_RESULT_NOT_CONNECTED",
    "LEAVE_RESULT_OK",
    "LEAVE_RESULT_VOICE_CONNECTION_FAILED",
    "SPEAK_RESULT_CROSS_GUILD_CHANNEL",
    "SPEAK_RESULT_MISSING_GUILD_ID",
    "SPEAK_RESULT_MISSING_TEXT",
    "SPEAK_RESULT_OK",
    "SPEAK_RESULT_PLAYBACK_TIMEOUT",
    "SPEAK_RESULT_QUEUED",
    "SPEAK_RESULT_QUEUE_FULL",
    "SPEAK_RESULT_UNKNOWN_ERROR",
    "SPEAK_RESULT_USER_LEFT_CHANNEL",
    "SPEAK_RESULT_USER_NOT_IN_CHANNEL",
    "SPEAK_RESULT_VOICE_CHANNEL_NOT_FOUND",
    "SPEAK_RESULT_VOICE_CONNECTION_FAILED",
    "SPEAK_RESULT_VOICE_PERMISSION_DENIED",
    "VOICE_CONTEXT_RESULT_MEMBER_REQUIRED",
    "VOICE_CONTEXT_RESULT_NOT_IN_CHANNEL",
    "VOICE_CONTEXT_RESULT_OK",
]
